name: Bumpversion release version.
description: Increases a project version with new releases.
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  current_version:
    description: 'The current project version'
    required: false
  new_version:
    description: 'The next project version'
    required: false
  paths:
    description: 'A list of file names to search and replace versions.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.paths }}
    - ${{ inputs.current_version }}
    - ${{ inputs.new_version }}
branding:
  icon: arrow-up
  color: green
