name: Sync release version.
description: Update files that reference a project version with new release number.
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  current_version:
    description: 'The current project version'
    required: false
  new_version:
    description: 'The next project version'
    required: false
  paths:
    description: 'A list of file names to search and replace versions.'
    required: true
  pattern:
    description: 'The pattern to match the location that needs to be updated'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.paths }}
    - ${{ inputs.current_version }}
    - ${{ inputs.new_version }}
    - ${{ inputs.pattern }}
branding:
  icon: arrow-up
  color: green
