name: Update release version.
on:
  release:
    types: [published]


jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumpversion release version.
        uses: tj-actions/bumpversion@v6.3
        id: bumpversion
        with:
          commit: true
          prefix: 'tj-actions/bumpversion@'
          paths: |
            README.md
      - name: pull-request-${{ steps.bumpversion.outputs.new_branch_name }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ steps.bumpversion.outputs.new_branch_name }}"
          destination_branch: "master"
          pr_title: "Upgraded from ${{ steps.bumpversion.outputs.old_version }} -> ${{ steps.bumpversion.outputs.new_version }}" 
          pr_reviewer: "jackton1"
          github_token: ${{ secrets.GITHUB_TOKEN }}
