name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test bumpversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bumpversion
        uses: ./
        id: bumpversion
        with:
          current_version: '1.0.1'
          paths: |
            test/README.md
            test/subdir/README.md
      - run: |
          cat test/README.md
          echo "------"
          cat test/subdir/README.md
